import Head from "next/head";
import React from "react";

function MetaHead() {
  return (
    <Head>
      <title>QR Generator</title>
      <meta name="description" content="Generated by vm qr generator" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

export default MetaHead;
