import Head from "next/head";
import React from "react";

function MetaHead() {
  return (
    <Head>
      <title>QR Generator</title>
      <meta name="description" content="Generated by vm qr generator" />
      <meta
        name="keywords"
        content="qr code generator, link to qr code generator, free qr code generator, qr generator online, online qr code generator"
      />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/qr-icon.ico" />
    </Head>
  );
}

export default MetaHead;
